### ISSUE TITLE
Encrypt Stored URLs, Usernames, Passwords?

### ISSUE THREAD

**Issue by Francewhoa** [excitoon/MultiPassDisarmed#2]
**Question**
Does this add on encrypt its stored URLs, usernames, and passwords? Or are they stored in plaintext? Or else?

**Challenge**
If the URLs, usernames, and passwords are stored in plaintext, there is a risk that a not authorized person with access to your computer will be able to read anything stored using the add-on. Such as Basic Authentication URL, username and passwords

**Suggested Resolution**
For stronger security, how about automatically encrypting the add on storage of URLs, usernames, and passwords? This could potentially significantly slow down a not authorized person to access such sensitive data.

**Note**
Related ticket at https://github.com/krtek4/MultiPass/issues/48

**Comment by bastien30** [comment]
@Francewhoa It seems that username, password and URLs are stored in plaintext in your firefox profil.
See the file /browser-extension-data/multipassdisarmed@random.supplies/storage.js.

+1 for encrypted storage of theses data :+1:

**Comment by mrodrig** [comment]
+1 for encrypting these values.

**Comment by excitoon** [comment]
Hi. Please move on with the duscussion in main repository. My fork is no longer needed because the add on successfully appeared in Firefox.
